server:
  port: 1234
spring:
  application:
    name: MiniProject
  datasource:
    url: jdbc:mysql://localhost:3306/MiniProjectDB?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 2000000
      refresh-token:
        expiration: 3000000